# Generated by Django 5.1.3 on 2024-12-03 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_profilemodel_country"),
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ratingmodel",
            name="agents",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_review",
                to="profiles.profilemodel",
            ),
        ),
    ]
