# Generated by Django 5.1.3 on 2024-11-29 14:36

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "primary_key_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        default="+91435533232", max_length=12, region=None
                    ),
                ),
                ("about_me", models.TextField()),
                ("license", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "profile_photo",
                    models.ImageField(default="/profile_default.png", upload_to=""),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Male", "Male"),
                            ("Female", "Female"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(default="INDIA", max_length=2),
                ),
                ("city", models.CharField(default="Nairobi", max_length=180)),
                (
                    "is_buyer",
                    models.BooleanField(
                        default=False, help_text="Are you looking to Buy a Property?"
                    ),
                ),
                (
                    "is_seller",
                    models.BooleanField(
                        default=False, help_text="Are you looking to sell a property?"
                    ),
                ),
                (
                    "is_agent",
                    models.BooleanField(default=False, help_text="Are you an agent?"),
                ),
                ("top_agent", models.BooleanField(default=False)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("num_reviews", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
