# Generated by Django 5.1.3 on 2024-11-30 05:49

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="country",
            field=django_countries.fields.CountryField(default="INDIA", max_length=250),
        ),
    ]
